### ISSUE TITLE
执行代码出现下面错误？请问是啥原因呢？

### ISSUE THREAD

**Issue by SmallerPig** [yangyifeng01/pycmpp#1]
``` python
smallerpig@zhuqi-MBP:~/Downloads/pycmpp-master$ python3 sms.py
{'length': 33, 'command_id': 2147483649, 'sequence_id': 1} {'Status': 0, 'AuthenticatorISMG': b'\x00\x009\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'Version': 0}
connect successfully
send thread start
recv thread start
contact thread start
[2001]
[2001, 2002]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "cmpp/cmppthread.py", line 130, in run
    h,b = self.__recv()
  File "/Users/smallerpig/Downloads/pycmpp-master/cmpp/cmpp.py", line 217, in recv
    maxlen,=struct.unpack('!L',length)
struct.error: unpack requires a bytes object of length 4

[Errno 32] Broken pipe


```

**Comment by zackzhangkai** [comment]
老兄，你的问题解决没有，我碰到了一样的问题 @SmallerPig

**Comment by SmallerPig** [comment]
好长时间过去了，不记得了！！ @kaizamm
